In [7]:
import tensorflow as tf
import numpy as np

In [23]:
# create a tensor object
t = tf.constant([[1,2,3], [4,5,6]])
print (t)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [24]:
# attributs of tensor object
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'int32'>


In [26]:
# indxing, same as numpy array
print(t[:, 1:])
print(t[...,1,np.newaxis])    # same as t[:,1,np.newaxis]

tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32)


In [28]:
# tensor operation
print(t + 10)
print(tf.square(t))
print(tf.transpose(t))
print(t @ tf.transpose(t))

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


In [35]:
# tensor vs numpy: play well with each other
a = np.array([2,4,5])
tf.constant(a)      # create tensor object from numpy array
t.numpy()           # convert tensor object to numpy array
tf.square(a)        # use tensor funciton to work on numpy array
np.square(t)

array([ 4, 16, 25])