In [5]:
import numpy as np

data = """
2.60	9.82	10.86	14.31	20.64	28.76
4.97	5.90	13.48	19.96	13.70	28.36
8.56	9.60	15.69	15.18	22.49	33.49
3.30	7.99	13.56	17.47	22.42	35.49
7.69	10.72	17.29	22.90	18.09	41.40
11.65	14.57	14.37	19.20	18.13	38.19
8.80	12.14	18.24	18.52	20.24	31.86
14.13	9.47	19.18	20.07	25.41	39.48
12.20	17.32	25.59	18.85	22.35	39.33
13.73	9.99	25.58	18.21	25.37	34.69
"""
arrays = [np.fromstring(line, sep='\t') for line in data.strip().split('\n')]
matrix = np.vstack(arrays)

In [6]:
# correlation coefficient
print(np.round(np.corrcoef(matrix, rowvar=False),2))

[[ 1.    0.51  0.78  0.35  0.5   0.59]
 [ 0.51  1.    0.5   0.09  0.17  0.52]
 [ 0.78  0.5   1.    0.29  0.54  0.47]
 [ 0.35  0.09  0.29  1.   -0.31  0.6 ]
 [ 0.5   0.17  0.54 -0.31  1.    0.33]
 [ 0.59  0.52  0.47  0.6   0.33  1.  ]]


In [ ]:
# norm
arr = np.array([[[1,2,3]],[[4,5,6]]])
np.linalg.norm(arr)

9.539392014169456

In [7]:
# degree between two vectors
v1 = matrix[:,2]
v2 = matrix[:,-1]
np.degrees(np.arccos(np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))))


13.380561193753945

In [ ]:
# vector projection
P1 = matrix[:,0]
R = matrix[:,-1]
Project = R*(np.dot(R, P1)/np.square(np.linalg.norm(R)))
print(Project)

[ 7.30471982  7.20312428  8.50608716  9.0140649  10.5151391   9.69983484
  8.09208531 10.02748048  9.98938215  8.81087381]


In [ ]:
# matrix inverse
A = np.matrix('0.2821 0 -.7197 0; .1515 0 0 -.8485; 0 0 1 1; .2078 .2078 -.7922 -.7922')
B = np.matrix('0; 0; 16; 0')
print(A)
x = np.linalg.inv(A)@B
print(x)

[[ 0.2821  0.     -0.7197  0.    ]
 [ 0.1515  0.      0.     -0.8485]
 [ 0.      0.      1.      1.    ]
 [ 0.2078  0.2078 -0.7922 -0.7922]]
[[ 0.2821  0.     -0.7197  0.    ]
 [ 0.1515  0.      0.     -0.8485]
 [ 0.      0.      1.      1.    ]
 [ 0.2078  0.2078 -0.7922 -0.7922]]
[[28.04462733]
 [32.95248528]
 [10.99262105]
 [ 5.00737895]]


In [12]:
# eighn value
x = np.matrix('4 1 1 1; 1 4 1 1; 1 1 4 1; 1 1 1 4')
L,V = np.linalg.eig(x)
V

matrix([[-0.8660254 ,  0.5       , -0.21122065,  0.19867985],
        [ 0.28867513,  0.5       ,  0.86224628, -0.06622662],
        [ 0.28867513,  0.5       , -0.32551282, -0.75447382],
        [ 0.28867513,  0.5       , -0.32551282,  0.62202058]])

In [4]:
L = np.array([12.95602953,-6.41176115, 2.45573162])
V = np.array([[-0.6524968,  -0.77828713,  0.64669434],
              [-0.37666498,  0.02430747, -0.61754811],
              [-0.65754956,  0.62743788,  0.44768377]])
V@np.diag(L)@V.T

array([[2.65927516, 2.32480427, 9.40077634],
       [2.32480427, 2.77089954, 2.43218071],
       [9.40077634, 2.43218071, 3.56982534]])

In [9]:
# confusion matrix

confusion = np.array([[223,11,15,9],
                     [14,198,10,8],
                     [16,14,195,7],
                     [18,13,10,239]])
np.sum(np.diag(confusion)/np.sum(confusion))
Recall = confusion[-1,-1]/np.sum(confusion[-1,:])
Precision = confusion[-1,-1]/np.sum(confusion[:,-1])
2 * (Precision * Recall) / (Precision + Recall)
confusion[2,2]/np.sum(confusion[:,2])

0.8478260869565217

In [10]:
# MAPE, R_sqr, adjust R_sqr
data = np.array([[157, 151],
 [208, 192],
 [123, 114],
 [176, 171],
 [176, 160],
 [134, 120],
 [192, 182],
 [203, 186],
 [190, 174],
 [187, 174],
 [192, 187],
 [214, 199],
 [138, 123],
 [121, 102],
 [135, 121],
 [168, 152],
 [117, 101],
 [206, 187],
 [147, 129],
 [155, 137]])
MAPE = np.sum(np.abs(data[:,0]-data[:,1])/data[:,1])/data.shape[0]
R_sqr = np.sum(np.square(np.abs(data[:,0]-data[:,1])))/np.sum(np.square(np.abs(data[:,0]-np.average(data[:,0]))))
1 - np.sum(np.square(data[:,0]-data[:,1]))/np.sum(np.square(data[:,0]-np.average(data[:,0])))

0.7803525713645798